syntax = "proto3";

package pricing;

// Описание сервиса ценообразования и его методов
service PricingService {
  // Метод для расчета стоимости поездки
  rpc CalculateFare (FareRequest) returns (FareResponse);
}

// Структура координат (Широта и Долгота)
message LatLng {
  double latitude = 1;
  double longitude = 2;
}

// Входные параметры запроса (Request)
message FareRequest {
  LatLng origin = 1;              // Координаты точки отправления (Адрес А)
  LatLng destination = 2;         // Координаты точки прибытия (Адрес Б)
  string promo_code = 3;          // Промокод (опционально)
  string client_id = 4;           // ID клиента для проверки персональных скидок
}

// Структура данных по конкретному тарифу
message TariffOption {
  string tariff_class = 1;        // Название тарифа (ECONOMY, COMFORT, BUSINESS)
  int64 total_fare = 2;           // Итоговая цена в копейках (150 руб 50 коп = 15050)
  string currency = 3;            // Валюта (RUB)
  int32 estimated_arrival_min = 4; // Расчетное время подачи машины в минутах
}

// Выходные параметры ответа (Response)
message FareResponse {
  string request_id = 1;                   // ID расчета стоимости
  repeated TariffOption tariff_options = 2; // Список доступных тарифов (массив)
}
